import type { Trip, Metric, TravelGoal } from './types'

export const mockTrips: Trip[] = [
  {
    id: 'trip-tokyo',
    destination: 'Tokyo',
    country: 'Japan',
    startDate: 'Jul 22',
    endDate: 'Jul 29',
    status: 'in-transit',
    travelers: 1,
    budgetUsed: 3200,
    budgetTotal: 4000,
    flightCode: 'NH 106',
  },
  {
    id: 'trip-vancouver',
    destination: 'Vancouver',
    country: 'Canada',
    startDate: 'Jul 24',
    endDate: 'Jul 27',
    status: 'delayed',
    travelers: 1,
    budgetUsed: 1100,
    budgetTotal: 1800,
    flightCode: 'AC 8891',
  },
  {
    id: 'trip-lisbon',
    destination: 'Lisbon',
    country: 'Portugal',
    startDate: 'Aug 14',
    endDate: 'Aug 21',
    status: 'upcoming',
    travelers: 2,
    budgetUsed: 450,
    budgetTotal: 2800,
    flightCode: 'TP 232',
  },
  {
    id: 'trip-reykjavik',
    destination: 'Reykjavík',
    country: 'Iceland',
    startDate: 'Sep 3',
    endDate: 'Sep 9',
    status: 'upcoming',
    travelers: 2,
    budgetUsed: 200,
    budgetTotal: 3100,
    flightCode: 'FI 632',
  },
  {
    id: 'trip-nairobi',
    destination: 'Nairobi',
    country: 'Kenya',
    startDate: 'May 10',
    endDate: 'May 19',
    status: 'completed',
    travelers: 1,
    budgetUsed: 2650,
    budgetTotal: 2650,
  },
  {
    id: 'trip-singapore',
    destination: 'Singapore',
    country: 'Singapore',
    startDate: 'Mar 2',
    endDate: 'Mar 8',
    status: 'completed',
    travelers: 3,
    budgetUsed: 3980,
    budgetTotal: 4200,
  },
]

export const mockMetrics: Metric[] = [
  {
    id: 'active-trips',
    label: 'Active Trips',
    value: 4,
    trend: 'up',
    trendLabel: '+1',
    accent: 'cyan',
  },
  {
    id: 'ytd-spend',
    label: 'YTD Spend',
    value: 11580,
    unit: '',
    trend: 'up',
    trendLabel: '12%',
    accent: false,
  },
  {
    id: 'miles-traveled',
    label: 'Miles Traveled',
    value: 38240,
    trend: 'up',
    trendLabel: '8%',
    accent: false,
  },
  {
    id: 'avg-trip-length',
    label: 'Avg Trip Length',
    value: 6.4,
    unit: 'd',
    precision: 1,
    trend: 'neutral',
    accent: false,
  },
]

export const mockGoal: TravelGoal = {
  id: 'annual-budget',
  title: '2026 Travel Budget Used',
  current: 11580,
  target: 18000,
  unit: 'USD',
  accent: 'cyan',
}

export const nextDeparture = {
  destination: 'Lisbon',
  flightCode: 'TP 232',
  date: 'Aug 14, 07:15',
}
