#!/usr/bin/env node
/**
 * Token generator.
 *
 * `src/tokens.json` is the single source of truth. This writes it out in the two
 * forms the project needs:
 *
 *   src/tokens.css  — @theme + :root blocks, imported by index.css (app + Storybook preview)
 *   src/tokens.ts   — the same values as JS, for Storybook's manager theme and the
 *                     Design Tokens story (the manager can't read CSS variables)
 *
 *   node scripts/build-tokens.mjs            regenerate both files
 *   node scripts/build-tokens.mjs --check    fail if either file is stale or hand-edited
 *
 * Zero dependencies — the project has no test runner on purpose.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join, relative } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const SOURCE = join(root, 'src/tokens.json')
const CSS_OUT = join(root, 'src/tokens.css')
const TS_OUT = join(root, 'src/tokens.ts')

const HEADER = 'GENERATED by scripts/build-tokens.mjs from src/tokens.json — do not hand-edit. Run `npm run tokens`.'

/* ── helpers ──────────────────────────────────────────────────────────── */

/** camelCase -> kebab-case */
const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()

/** Drop `$description`-style keys used for documentation inside tokens.json. */
const entries = (obj) => Object.entries(obj).filter(([k]) => !k.startsWith('$'))

/** A token is either a bare value or `{ value, note }`. */
const valueOf = (t) => (typeof t === 'object' && t !== null ? t.value : t)
const noteOf = (t) => (typeof t === 'object' && t !== null ? t.note : undefined)

/** Single-quoted TS string, unless the value itself holds single quotes (font stacks). */
const tsString = (v) => (v.includes("'") ? JSON.stringify(v) : `'${v}'`)

function fail(msg) {
  console.error(`\x1b[31m${msg}\x1b[0m`)
  process.exit(1)
}

/* ── load + validate ──────────────────────────────────────────────────── */

const tokens = JSON.parse(readFileSync(SOURCE, 'utf8'))
const { colors, colorAliases, fonts, radius, shadows, spacing, typeScale, motion } = tokens

const darkKeys = entries(colors.dark).map(([k]) => k)
const lightKeys = entries(colors.light).map(([k]) => k)
{
  const missing = [
    ...darkKeys.filter((k) => !lightKeys.includes(k)).map((k) => `colors.light.${k} is missing`),
    ...lightKeys.filter((k) => !darkKeys.includes(k)).map((k) => `colors.dark.${k} is missing`),
  ]
  if (missing.length) fail(`tokens.json: every color needs a dark AND light value\n  ${missing.join('\n  ')}`)
}

for (const [alias, target] of entries(colorAliases)) {
  if (!darkKeys.includes(target)) fail(`tokens.json: colorAliases.${alias} points at unknown color "${target}"`)
}

for (const [role, t] of entries(typeScale)) {
  if (!(t.font in fonts)) fail(`tokens.json: typeScale.${role}.font "${t.font}" is not a key in fonts`)
}

// Spacing is documentation only: it has to stay on Tailwind's default 4px step,
// or the Design Tokens story promises a size no utility can produce.
for (const [key, px] of entries(spacing)) {
  if (px % 4 !== 0) fail(`tokens.json: spacing.${key} = ${px} is not a multiple of 4 — Tailwind's default scale can't express it`)
}

/* ── CSS ──────────────────────────────────────────────────────────────── */

function cssDecl(name, token) {
  const note = noteOf(token)
  return `  --${name}: ${valueOf(token)};${note ? ` /* ${note} */` : ''}`
}

function renderCss() {
  const staticTheme = [
    ...entries(fonts).map(([k, v]) => cssDecl(`font-${kebab(k)}`, v)),
    '',
    ...entries(radius).map(([k, v]) => cssDecl(`radius-${kebab(k)}`, v)),
    '',
    ...entries(shadows).map(([k, v]) => cssDecl(`shadow-${kebab(k)}`, v)),
    '',
    '  /* Type scale — size + line-height + tracking + weight per role. */',
    ...entries(typeScale).flatMap(([k, t], i) => {
      const role = `text-${kebab(k)}`
      return [
        ...(i ? [''] : []),
        `  --${role}: ${t.size};`,
        `  --${role}--line-height: ${t.lh};`,
        `  --${role}--letter-spacing: ${t.ls};`,
        `  --${role}--font-weight: ${t.weight};`,
      ]
    }),
  ]

  const aliases = [
    ...darkKeys.map((k) => `  --color-${kebab(k)}: var(--${kebab(k)});`),
    '',
    '  /* shadcn-required aliases — mapped onto our semantic surfaces, not a second palette */',
    ...entries(colorAliases).map(([k, target]) => `  --color-${kebab(k)}: var(--${kebab(target)});`),
  ]

  const modeVars = (mode) => entries(colors[mode]).map(([k, v]) => cssDecl(kebab(k), v))

  return `/* ${HEADER} */

/* 1. STATIC tokens → become Tailwind utilities (fonts, radius, shadows, type scale). */
@theme {
${staticTheme.join('\n')}
}

/* 2. SEMANTIC aliases → map utility names to runtime vars (themeable at use-site). */
@theme inline {
${aliases.join('\n')}
}

/* 3. VALUES — dark by default, light via [data-theme="light"]. OS preference is not
      consulted: index.html ships data-theme="dark" so first paint is stable. */
:root {
${modeVars('dark').join('\n')}

${entries(motion).map(([k, v]) => cssDecl(kebab(k), v)).join('\n')}
}

:root[data-theme='light'] {
${modeVars('light').join('\n')}
}
`
}

/* ── TS ───────────────────────────────────────────────────────────────── */

function tsObject(obj, indent = '  ', format = (v) => tsString(valueOf(v))) {
  return entries(obj)
    .map(([k, v]) => `${indent}${k}: ${format(v)},`)
    .join('\n')
}

function renderTs() {
  const typeRows = entries(typeScale)
    .map(
      ([k, t]) =>
        `  ${k}: { size: ${tsString(t.size)}, weight: ${t.weight}, lh: ${tsString(t.lh)}, ls: ${tsString(t.ls)}, font: ${tsString(t.font)} },`,
    )
    .join('\n')

  return `// ${HEADER}

export const colors = {
  dark: {
${tsObject(colors.dark, '    ')}
  },
  light: {
${tsObject(colors.light, '    ')}
  },
} as const

export type ThemeMode = keyof typeof colors
export type ColorKey = keyof typeof colors.dark

export const fonts = {
${tsObject(fonts)}
} as const

export const radius = {
${tsObject(radius)}
} as const

export const shadows = {
${tsObject(shadows)}
} as const

export const spacing = {
${tsObject(spacing, '  ', (v) => String(v))}
} as const

export interface TypeRole {
  size: string
  weight: number
  lh: string
  ls: string
  font: ${Object.keys(fonts).map(tsString).join(' | ')}
}

export const typeScale: Record<string, TypeRole> = {
${typeRows}
}

export const motion = {
${tsObject(motion)}
} as const
`
}

/* ── write or check ───────────────────────────────────────────────────── */

const outputs = [
  [CSS_OUT, renderCss()],
  [TS_OUT, renderTs()],
]

if (process.argv.includes('--check')) {
  const stale = outputs.filter(([file, text]) => !existsSync(file) || readFileSync(file, 'utf8') !== text)
  if (stale.length) {
    fail(
      `✗ generated tokens are out of date: ${stale.map(([f]) => relative(root, f)).join(', ')}\n` +
        '  Edit src/tokens.json (not the generated files), then run `npm run tokens`.',
    )
  }
  console.log('\x1b[32m✓ tokens up to date\x1b[0m — tokens.css and tokens.ts match tokens.json')
} else {
  for (const [file, text] of outputs) writeFileSync(file, text)
  console.log(`\x1b[32m✓ tokens generated\x1b[0m — ${outputs.map(([f]) => relative(root, f)).join(', ')}`)
}
