#!/usr/bin/env node
/**
 * Token generator.
 *
 * `src/tokens.json` is the single source of truth. This writes it out as the files
 * the project needs.
 *
 * Colors are two layers: `palette` (primitives, e.g. cyan-400) and `colors` (semantic,
 * e.g. primary), where every semantic color references a palette key as "{cyan400}".
 * The CSS is written as the same two layers, both imported by index.css (app + Storybook preview):
 *
 *   src/primitives.css — palette + motion, plain :root vars
 *   src/semantics.css  — @theme roles + Tailwind color aliases + themed :root values
 *   src/tokens.ts   — the same values as JS, for Storybook's manager theme and the
 *                     Foundation pages (the manager can't read CSS variables)
 *
 *   node scripts/build-tokens.mjs            regenerate all three files
 *   node scripts/build-tokens.mjs --check    fail if any file is stale or hand-edited
 *
 * Zero dependencies — the project has no test runner on purpose.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join, relative } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const SOURCE = join(root, 'src/tokens.json')
const PRIMITIVES_OUT = join(root, 'src/primitives.css')
const SEMANTICS_OUT = join(root, 'src/semantics.css')
const TS_OUT = join(root, 'src/tokens.ts')

const HEADER = 'GENERATED by scripts/build-tokens.mjs from src/tokens.json — do not hand-edit. Run `npm run tokens`.'

/* ── helpers ──────────────────────────────────────────────────────────── */

/** camelCase -> kebab-case */
const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()

/** Drop `$description`-style keys used for documentation inside tokens.json. */
const entries = (obj) => Object.entries(obj).filter(([k]) => !k.startsWith('$'))

/** A token is either a bare value or `{ value, note }`. */
const valueOf = (t) => (typeof t === 'object' && t !== null ? t.value : t)
const noteOf = (t) => (typeof t === 'object' && t !== null ? t.note : undefined)

/** Single-quoted TS string, unless the value itself holds single quotes (font stacks). */
const tsString = (v) => (v.includes("'") ? JSON.stringify(v) : `'${v}'`)

/** Palette key -> CSS var name: `ink950` -> `ink-950`, `amber750` -> `amber-750`. */
const paletteName = (k) => kebab(k).replace(/([a-z])(\d)/g, '$1-$2')

/** `{ink950}` -> `ink950`, or null if the string isn't a reference. */
const refKey = (v) => (typeof v === 'string' && /^\{[A-Za-z0-9]+\}$/.test(v) ? v.slice(1, -1) : null)

/** `#22d3ee` + 0.1 -> `rgba(34, 211, 238, 0.1)` */
function hexToRgba(hex, alpha) {
  const n = parseInt(hex.slice(1), 16)
  return `rgba(${(n >> 16) & 255}, ${(n >> 8) & 255}, ${n & 255}, ${alpha})`
}

function fail(msg) {
  console.error(`\x1b[31m${msg}\x1b[0m`)
  process.exit(1)
}

/* ── load + validate ──────────────────────────────────────────────────── */

const tokens = JSON.parse(readFileSync(SOURCE, 'utf8'))
const { palette, colors, colorAliases, fonts, radius, shadows, spacing, typeScale, motion } = tokens

for (const [k, v] of entries(palette)) {
  if (!/^#[0-9a-f]{6}$/i.test(valueOf(v))) fail(`tokens.json: palette.${k} must be a 6-digit hex, got "${valueOf(v)}"`)
}

// Semantic colors must reference the palette — a raw value here would skip the primitive layer.
for (const mode of ['dark', 'light']) {
  for (const [k, t] of entries(colors[mode])) {
    const key = refKey(valueOf(t))
    if (!key) fail(`tokens.json: colors.${mode}.${k} must reference the palette as "{key}", got "${valueOf(t)}"`)
    if (!(key in palette)) fail(`tokens.json: colors.${mode}.${k} points at unknown palette key "${key}"`)
  }
}

/** Palette hex a semantic color points at. */
const baseHex = (t) => valueOf(palette[refKey(valueOf(t))])

/** Literal value of a semantic color — hex, or rgba for a tint. What the TS export and Storybook see. */
const resolveColor = (t) => (t.alpha != null ? hexToRgba(baseHex(t), t.alpha) : baseHex(t))

/** Human-readable source, e.g. `cyan-400` or `cyan-400 @ 10%`. */
const sourceOf = (t) => {
  const name = paletteName(refKey(valueOf(t)))
  return t.alpha != null ? `${name} @ ${Math.round(t.alpha * 100)}%` : name
}

const darkKeys = entries(colors.dark).map(([k]) => k)
const lightKeys = entries(colors.light).map(([k]) => k)
{
  const missing = [
    ...darkKeys.filter((k) => !lightKeys.includes(k)).map((k) => `colors.light.${k} is missing`),
    ...lightKeys.filter((k) => !darkKeys.includes(k)).map((k) => `colors.dark.${k} is missing`),
  ]
  if (missing.length) fail(`tokens.json: every color needs a dark AND light value\n  ${missing.join('\n  ')}`)
}

for (const [alias, target] of entries(colorAliases)) {
  if (!darkKeys.includes(target)) fail(`tokens.json: colorAliases.${alias} points at unknown color "${target}"`)
}

for (const [role, t] of entries(typeScale)) {
  if (!(t.font in fonts)) fail(`tokens.json: typeScale.${role}.font "${t.font}" is not a key in fonts`)
}

// Spacing is documentation only: it has to stay on Tailwind's default 4px step,
// or the Primitives page promises a size no utility can produce.
for (const [key, px] of entries(spacing)) {
  if (px % 4 !== 0) fail(`tokens.json: spacing.${key} = ${px} is not a multiple of 4 — Tailwind's default scale can't express it`)
}

/* ── CSS ──────────────────────────────────────────────────────────────── */

function cssDecl(name, token) {
  const note = noteOf(token)
  return `  --${name}: ${valueOf(token)};${note ? ` /* ${note} */` : ''}`
}

function renderSemanticsCss() {
  const staticTheme = [
    ...entries(fonts).map(([k, v]) => cssDecl(`font-${kebab(k)}`, v)),
    '',
    ...entries(radius).map(([k, v]) => cssDecl(`radius-${kebab(k)}`, v)),
    '',
    ...entries(shadows).map(([k, v]) => cssDecl(`shadow-${kebab(k)}`, v)),
    '',
    '  /* Type scale — size + line-height + tracking + weight per role. */',
    ...entries(typeScale).flatMap(([k, t], i) => {
      const role = `text-${kebab(k)}`
      return [
        ...(i ? [''] : []),
        `  --${role}: ${t.size};`,
        `  --${role}--line-height: ${t.lh};`,
        `  --${role}--letter-spacing: ${t.ls};`,
        `  --${role}--font-weight: ${t.weight};`,
      ]
    }),
  ]

  const aliases = [
    ...darkKeys.map((k) => `  --color-${kebab(k)}: var(--${kebab(k)});`),
    '',
    '  /* shadcn-required aliases — mapped onto our semantic surfaces, not a second palette */',
    ...entries(colorAliases).map(([k, target]) => `  --color-${kebab(k)}: var(--${kebab(target)});`),
  ]

  // Solid colors point at the palette var. Tints are baked to rgba (a var can't take an
  // alpha) and carry their source in a comment instead.
  const modeVars = (mode) =>
    entries(colors[mode]).map(([k, t]) => {
      if (t.alpha == null) return cssDecl(kebab(k), { value: `var(--${paletteName(refKey(valueOf(t)))})`, note: noteOf(t) })
      return cssDecl(kebab(k), { value: resolveColor(t), note: [sourceOf(t), noteOf(t)].filter(Boolean).join(' — ') })
    })

  return `/* ${HEADER} */

/* LAYER 2: SEMANTIC TOKENS — named by job, not by value. Components use these. */

/* 1. STATIC roles → become Tailwind utilities (fonts, radius, shadows, type scale).
      Not themed, so they hold values directly. */
@theme {
${staticTheme.join('\n')}
}

/* 2. COLOR utilities → map Tailwind color names (bg-primary…) to the runtime vars in 3. */
@theme inline {
${aliases.join('\n')}
}

/* 3. COLOR values → each points at a palette primitive in primitives.css. Dark by default,
      light via [data-theme="light"]. OS preference is not consulted: index.html ships
      data-theme="dark" so first paint is stable. */
:root {
${modeVars('dark').join('\n')}
}

:root[data-theme='light'] {
${modeVars('light').join('\n')}
}
`
}

function renderPrimitivesCss() {
  return `/* ${HEADER} */

/* LAYER 1: PRIMITIVE TOKENS — raw values, named by what they are. Theme-independent,
   and not Tailwind utilities on purpose: components use the semantic tokens in
   semantics.css, which point at these. */
:root {
  /* Palette */
${entries(palette).map(([k, v]) => cssDecl(paletteName(k), v)).join('\n')}

  /* Motion */
${entries(motion).map(([k, v]) => cssDecl(kebab(k), v)).join('\n')}
}
`
}

/* ── TS ───────────────────────────────────────────────────────────────── */

function tsObject(obj, indent = '  ', format = (v) => tsString(valueOf(v))) {
  return entries(obj)
    .map(([k, v]) => `${indent}${k}: ${format(v)},`)
    .join('\n')
}

function renderTs() {
  const typeRows = entries(typeScale)
    .map(
      ([k, t]) =>
        `  ${k}: { size: ${tsString(t.size)}, weight: ${t.weight}, lh: ${tsString(t.lh)}, ls: ${tsString(t.ls)}, font: ${tsString(t.font)} },`,
    )
    .join('\n')

  const resolved = (t) => tsString(resolveColor(t))
  const source = (t) => tsString(sourceOf(t))

  return `// ${HEADER}

/** Primitives — raw values, named by what they are. */
export const palette = {
${entries(palette)
  .map(([k, v]) => `  ${tsString(paletteName(k))}: ${tsString(valueOf(v))},`)
  .join('\n')}
} as const

/** Semantic colors, resolved to literal values (Storybook's manager can't read CSS vars). */
export const colors = {
  dark: {
${tsObject(colors.dark, '    ', resolved)}
  },
  light: {
${tsObject(colors.light, '    ', resolved)}
  },
} as const

/** Which palette primitive each semantic color points at, e.g. \`primary: 'cyan-400'\`. */
export const colorSources = {
  dark: {
${tsObject(colors.dark, '    ', source)}
  },
  light: {
${tsObject(colors.light, '    ', source)}
  },
} as const

/** Extra Tailwind color names shadcn expects, each mapped onto a semantic color, e.g. \`muted: 'cardRaised'\`. */
export const colorAliases = {
${tsObject(colorAliases)}
} as const

export type ThemeMode = keyof typeof colors
export type ColorKey = keyof typeof colors.dark

export const fonts = {
${tsObject(fonts)}
} as const

export const radius = {
${tsObject(radius)}
} as const

export const shadows = {
${tsObject(shadows)}
} as const

export const spacing = {
${tsObject(spacing, '  ', (v) => String(v))}
} as const

export interface TypeRole {
  size: string
  weight: number
  lh: string
  ls: string
  font: ${Object.keys(fonts).map(tsString).join(' | ')}
}

export const typeScale: Record<string, TypeRole> = {
${typeRows}
}

export const motion = {
${tsObject(motion)}
} as const
`
}

/* ── write or check ───────────────────────────────────────────────────── */

const outputs = [
  [PRIMITIVES_OUT, renderPrimitivesCss()],
  [SEMANTICS_OUT, renderSemanticsCss()],
  [TS_OUT, renderTs()],
]

if (process.argv.includes('--check')) {
  const stale = outputs.filter(([file, text]) => !existsSync(file) || readFileSync(file, 'utf8') !== text)
  if (stale.length) {
    fail(
      `✗ generated tokens are out of date: ${stale.map(([f]) => relative(root, f)).join(', ')}\n` +
        '  Edit src/tokens.json (not the generated files), then run `npm run tokens`.',
    )
  }
  console.log('\x1b[32m✓ tokens up to date\x1b[0m — primitives.css, semantics.css and tokens.ts match tokens.json')
} else {
  for (const [file, text] of outputs) writeFileSync(file, text)
  console.log(`\x1b[32m✓ tokens generated\x1b[0m — ${outputs.map(([f]) => relative(root, f)).join(', ')}`)
}
