// GENERATED by scripts/build-tokens.mjs from src/tokens.json — do not hand-edit. Run `npm run tokens`.

/** Primitives — raw values, named by what they are. */
export const palette = {
  'white': '#ffffff',
  'ink-25': '#f8fbfd',
  'ink-50': '#f4f7fa',
  'ink-75': '#eef4f9',
  'ink-100': '#eef2f6',
  'ink-200': '#d7dee6',
  'ink-300': '#b8c4cf',
  'ink-500': '#828e9a',
  'ink-600': '#5f6a78',
  'ink-700': '#414c59',
  'ink-800': '#263140',
  'ink-850': '#1a2129',
  'ink-900': '#12181f',
  'ink-925': '#0d1420',
  'ink-950': '#0a0e14',
  'ink-975': '#060a10',
  'cyan-300': '#67e8f9',
  'cyan-400': '#22d3ee',
  'cyan-600': '#0891b2',
  'cyan-700': '#0e7490',
  'amber-400': '#fbbf24',
  'amber-700': '#b45309',
  'amber-750': '#a94d08',
  'violet-400': '#a78bfa',
  'violet-600': '#7c3aed',
  'red-400': '#f87171',
  'red-600': '#dc2626',
} as const

/** Semantic colors, resolved to literal values (Storybook's manager can't read CSS vars). */
export const colors = {
  dark: {
    background: '#0a0e14',
    foreground: '#eef4f9',
    foregroundStrong: '#f8fbfd',
    foregroundBody: '#b8c4cf',
    foregroundMuted: '#828e9a',
    card: '#12181f',
    cardRaised: '#1a2129',
    border: '#263140',
    input: '#263140',
    primary: '#22d3ee',
    primaryForeground: '#0a0e14',
    primaryTint: 'rgba(34, 211, 238, 0.1)',
    amber: '#fbbf24',
    amberTint: 'rgba(251, 191, 36, 0.1)',
    violet: '#a78bfa',
    violetTint: 'rgba(167, 139, 250, 0.1)',
    destructive: '#f87171',
    ring: '#67e8f9',
  },
  light: {
    background: '#f4f7fa',
    foreground: '#0d1420',
    foregroundStrong: '#060a10',
    foregroundBody: '#414c59',
    foregroundMuted: '#5f6a78',
    card: '#ffffff',
    cardRaised: '#eef2f6',
    border: '#d7dee6',
    input: '#d7dee6',
    primary: '#0e7490',
    primaryForeground: '#ffffff',
    primaryTint: 'rgba(14, 116, 144, 0.12)',
    amber: '#a94d08',
    amberTint: 'rgba(180, 83, 9, 0.12)',
    violet: '#7c3aed',
    violetTint: 'rgba(124, 58, 237, 0.12)',
    destructive: '#dc2626',
    ring: '#0891b2',
  },
} as const

/** Which palette primitive each semantic color points at, e.g. `primary: 'cyan-400'`. */
export const colorSources = {
  dark: {
    background: 'ink-950',
    foreground: 'ink-75',
    foregroundStrong: 'ink-25',
    foregroundBody: 'ink-300',
    foregroundMuted: 'ink-500',
    card: 'ink-900',
    cardRaised: 'ink-850',
    border: 'ink-800',
    input: 'ink-800',
    primary: 'cyan-400',
    primaryForeground: 'ink-950',
    primaryTint: 'cyan-400 @ 10%',
    amber: 'amber-400',
    amberTint: 'amber-400 @ 10%',
    violet: 'violet-400',
    violetTint: 'violet-400 @ 10%',
    destructive: 'red-400',
    ring: 'cyan-300',
  },
  light: {
    background: 'ink-50',
    foreground: 'ink-925',
    foregroundStrong: 'ink-975',
    foregroundBody: 'ink-700',
    foregroundMuted: 'ink-600',
    card: 'white',
    cardRaised: 'ink-100',
    border: 'ink-200',
    input: 'ink-200',
    primary: 'cyan-700',
    primaryForeground: 'white',
    primaryTint: 'cyan-700 @ 12%',
    amber: 'amber-750',
    amberTint: 'amber-700 @ 12%',
    violet: 'violet-600',
    violetTint: 'violet-600 @ 12%',
    destructive: 'red-600',
    ring: 'cyan-600',
  },
} as const

/** Extra Tailwind color names shadcn expects, each mapped onto a semantic color, e.g. `muted: 'cardRaised'`. */
export const colorAliases = {
  cardForeground: 'foreground',
  destructiveForeground: 'background',
  muted: 'cardRaised',
  mutedForeground: 'foregroundMuted',
  secondary: 'cardRaised',
  secondaryForeground: 'foreground',
  accent: 'cardRaised',
  accentForeground: 'foreground',
  popover: 'card',
  popoverForeground: 'foreground',
} as const

export type ThemeMode = keyof typeof colors
export type ColorKey = keyof typeof colors.dark

export const fonts = {
  display: "'Space Grotesk', sans-serif",
  body: "'Inter', sans-serif",
  mono: "'JetBrains Mono', monospace",
} as const

export const radius = {
  card: '0.875rem',
  btn: '0.625rem',
  icon: '0.75rem',
  chip: '0.375rem',
  pill: '9999px',
} as const

export const shadows = {
  cyan: '0 4px 14px rgba(34, 211, 238, 0.22)',
  cyanHover: '0 8px 24px rgba(34, 211, 238, 0.32)',
} as const

export const spacing = {
  sp1: 4,
  sp2: 8,
  sp3: 12,
  sp4: 16,
  sp5: 24,
  sp6: 32,
  sp7: 48,
  sp8: 64,
} as const

export interface TypeRole {
  size: string
  weight: number
  lh: string
  ls: string
  font: 'display' | 'body' | 'mono'
}

export const typeScale: Record<string, TypeRole> = {
  displayXl: { size: '44px', weight: 600, lh: '1.05', ls: '-0.02em', font: 'display' },
  displayLg: { size: '30px', weight: 600, lh: '1.1', ls: '-0.02em', font: 'display' },
  heading: { size: '20px', weight: 600, lh: '1.2', ls: '-0.01em', font: 'display' },
  body: { size: '15px', weight: 400, lh: '1.5', ls: '0', font: 'body' },
  bodySm: { size: '13px', weight: 400, lh: '1.45', ls: '0', font: 'body' },
  label: { size: '11px', weight: 500, lh: '1.3', ls: '0.06em', font: 'mono' },
  numeral: { size: '15px', weight: 500, lh: '1.3', ls: '0', font: 'mono' },
}

export const motion = {
  easeOutExpo: 'cubic-bezier(0.16, 1, 0.3, 1)',
  durFast: '150ms',
  durBase: '260ms',
  durSlow: '480ms',
  durStagger: '60ms',
} as const
